from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtGui import QPixmap, QIntValidator

from Lab2.utils import np_array_to_pixmap

from Lab2.events import event_manager


class CannyFilterWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, **kwargs) -> None:
        super().__init__(parent, **kwargs)

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_20 = QtWidgets.QFrame(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.formLayout_4.setObjectName("formLayout_4")
        self.gaussian_text = QtWidgets.QLabel(self.frame_20)
        self.gaussian_text.setObjectName("gaussian_text")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gaussian_text)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_12)
        self.minthreshold_text = QtWidgets.QLabel(self.frame_20)
        self.minthreshold_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.minthreshold_text.setObjectName("minthreshold_text")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.minthreshold_text)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_13)
        self.maxthreshold_text = QtWidgets.QLabel(self.frame_20)
        self.maxthreshold_text.setObjectName("maxthreshold_text")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.maxthreshold_text)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_20)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_14)
        self.gridLayout_4.addLayout(self.formLayout_4, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_10.addWidget(self.pushButton_3)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 4, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_20)
        self.frame_17 = QtWidgets.QFrame(self.tab_2)

        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.image_text = QtWidgets.QLabel(self.frame_18)
        self.image_text.setAlignment(QtCore.Qt.AlignCenter)
        self.image_text.setObjectName("image_text")
        self.gridLayout_12.addWidget(self.image_text, 0, 0, 1, 1)
        self.gradientx_text = QtWidgets.QLabel(self.frame_18)
        self.gradientx_text.setAlignment(QtCore.Qt.AlignCenter)
        self.gradientx_text.setObjectName("gradientx_text")
        self.gridLayout_12.addWidget(self.gradientx_text, 0, 1, 1, 1)
        self.maxima_text = QtWidgets.QLabel(self.frame_18)
        self.maxima_text.setAlignment(QtCore.Qt.AlignCenter)
        self.maxima_text.setObjectName("maxima_text")
        self.gridLayout_12.addWidget(self.maxima_text, 0, 2, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gradientx_label = QtWidgets.QLabel(self.frame_19)
        self.gradientx_label.setFrameShape(QtWidgets.QFrame.Box)
        self.gradientx_label.setText("")
        self.gradientx_label.setObjectName("gradientx_label")
        self.gridLayout_13.addWidget(self.gradientx_label, 0, 1, 1, 1)
        self.base_image_label = QtWidgets.QLabel(self.frame_19)
        self.base_image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.base_image_label.setText("")
        self.base_image_label.setObjectName("label_31")
        self.gridLayout_13.addWidget(self.base_image_label, 0, 0, 1, 1)
        self.localmaxima_label = QtWidgets.QLabel(self.frame_19)
        self.localmaxima_label.setFrameShape(QtWidgets.QFrame.Box)
        self.localmaxima_label.setText("")
        self.localmaxima_label.setObjectName("localmaxima_label")
        self.gridLayout_13.addWidget(self.localmaxima_label, 0, 2, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_19)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.frame_13 = QtWidgets.QFrame(self.tab_2)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.smoothed_text = QtWidgets.QLabel(self.frame_15)
        self.smoothed_text.setAlignment(QtCore.Qt.AlignCenter)
        self.smoothed_text.setObjectName("smoothed_text")
        self.gridLayout_10.addWidget(self.smoothed_text, 0, 0, 1, 1)
        self.gradienty_text = QtWidgets.QLabel(self.frame_15)
        self.gradienty_text.setAlignment(QtCore.Qt.AlignCenter)
        self.gradienty_text.setObjectName("gradienty_text")
        self.gridLayout_10.addWidget(self.gradienty_text, 0, 1, 1, 1)
        self.finalimage_text = QtWidgets.QLabel(self.frame_15)
        self.finalimage_text.setAlignment(QtCore.Qt.AlignCenter)
        self.finalimage_text.setObjectName("finalimage_text")
        self.gridLayout_10.addWidget(self.finalimage_text, 0, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_13)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.smoothed_label = QtWidgets.QLabel(self.frame_16)
        self.smoothed_label.setFrameShape(QtWidgets.QFrame.Box)
        self.smoothed_label.setText("")
        self.smoothed_label.setObjectName("smoothed_label")
        self.gridLayout_11.addWidget(self.smoothed_label, 0, 0, 1, 1)
        self.gradienty_label = QtWidgets.QLabel(self.frame_16)
        self.gradienty_label.setFrameShape(QtWidgets.QFrame.Box)
        self.gradienty_label.setText("")
        self.gradienty_label.setObjectName("gradienty_label")
        self.gridLayout_11.addWidget(self.gradienty_label, 0, 1, 1, 1)
        self.final_label = QtWidgets.QLabel(self.frame_16)
        self.final_label.setFrameShape(QtWidgets.QFrame.Box)
        self.final_label.setText("")
        self.final_label.setObjectName("final_label")
        self.gridLayout_11.addWidget(self.final_label, 0, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_16)
        self.verticalLayout_9.addWidget(self.frame_13)

        self.lineEdit_12.textChanged.connect(lambda x: event_manager.trigger("on_gaussian_filter_size_changed", x))
        self.lineEdit_13.textChanged.connect(lambda x: event_manager.trigger("on_min_canny_threshold_changed", x))
        self.lineEdit_14.textChanged.connect(lambda x: event_manager.trigger("on_max_canny_threshold_changed", x))

        self.pushButton_3.clicked.connect(lambda: event_manager.trigger("on_apply_canny_filter"))

        event_manager.register("on_load_image", self.update_image)
        event_manager.register("on_canny_image_result", self.update_result_image)

        self.setLayout(self.verticalLayout_9)
        self.retranslate_ui()


    def update_image(self, filepath:str):
        pixmap = QPixmap(filepath)
        self.base_image_label.setPixmap(pixmap)

    def update_result_image(self, image_name, image):
        pixmap = np_array_to_pixmap(image)
        if image_name == "gradient_x":
            self.gradientx_label.setPixmap(pixmap)
        elif image_name == "gradient_y":
            self.gradienty_label.setPixmap(pixmap)
        elif image_name == "local_maxima":
            self.localmaxima_label.setPixmap(pixmap)
        elif image_name == "smoothed":
            self.smoothed_label.setPixmap(pixmap)
        elif image_name == "final":
            self.final_label.setPixmap(pixmap)


    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.gaussian_text.setText(_translate("Lab2_Window", "Gaussian Filter Size"))
        self.minthreshold_text.setText(_translate("Lab2_Window", "Min Threshold"))
        self.maxthreshold_text.setText(_translate("Lab2_Window", "Max Threshold"))
        self.pushButton_3.setText(_translate("Lab2_Window", "Apply Filter"))
        self.image_text.setText(_translate("Lab2_Window", "Original Image"))
        self.gradientx_text.setText(_translate("Lab2_Window", "Gradient X"))
        self.maxima_text.setText(_translate("Lab2_Window", "Local Maxima"))
        self.smoothed_text.setText(_translate("Lab2_Window", "Smoothed Image"))
        self.gradienty_text.setText(_translate("Lab2_Window", "Gradient Y"))
        self.finalimage_text.setText(_translate("Lab2_Window", "Final Contour Image"))