from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtGui import QPixmap

from Lab2.utils import np_array_to_pixmap

from Lab2.events import event_manager



class FrequencyFilterWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, **kwargs) -> None:
        super().__init__(parent, **kwargs)

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_14 = QtWidgets.QFrame(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 3, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.formLayout.setObjectName("formLayout")
        self.cutoff_text = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutoff_text.sizePolicy().hasHeightForWidth())
        self.cutoff_text.setSizePolicy(sizePolicy)
        self.cutoff_text.setMinimumSize(QtCore.QSize(145, 0))
        self.cutoff_text.setObjectName("cutoff_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.cutoff_text)
        self.cutoff_edit = QtWidgets.QLineEdit(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutoff_edit.sizePolicy().hasHeightForWidth())
        self.cutoff_edit.setSizePolicy(sizePolicy)
        self.cutoff_edit.setObjectName("cutoff_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cutoff_edit)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.n_butterworth_text = QtWidgets.QLabel(self.frame_14)
        self.n_butterworth_text.setObjectName("n_butterworth_text")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.n_butterworth_text)
        self.n_butter_edit = QtWidgets.QLineEdit(self.frame_14)
        self.n_butter_edit.setObjectName("n_butter_edit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.n_butter_edit)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.gridLayout_9.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 5, 1, 1)

        self.verticalLayout_4 = QtWidgets.QHBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.apply_ideal_lowpass_btn = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_ideal_lowpass_btn.sizePolicy().hasHeightForWidth())
        self.apply_ideal_lowpass_btn.setSizePolicy(sizePolicy)
        self.apply_ideal_lowpass_btn.setObjectName("apply_ideal_lowpass_btn")
        self.verticalLayout_4.addWidget(self.apply_ideal_lowpass_btn)
        
        self.apply_ideal_highpass_btn = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_ideal_highpass_btn.sizePolicy().hasHeightForWidth())
        self.apply_ideal_highpass_btn.setSizePolicy(sizePolicy)
        self.apply_ideal_highpass_btn.setObjectName("apply_ideal_highpass_btn")
        self.verticalLayout_4.addWidget(self.apply_ideal_highpass_btn)


        self.apply_butter_lowpass_btn = QtWidgets.QPushButton(self.frame_14)
        self.apply_butter_lowpass_btn.setObjectName("apply_butter_lowpass_btn")
        self.verticalLayout_4.addWidget(self.apply_butter_lowpass_btn)

        self.apply_butter_highpass_btn = QtWidgets.QPushButton(self.frame_14)
        self.apply_butter_highpass_btn.setObjectName("apply_butter_highpass_btn")
        self.verticalLayout_4.addWidget(self.apply_butter_highpass_btn)

        self.gridLayout_9.addLayout(self.verticalLayout_4, 0, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_txt = QtWidgets.QLabel(self.frame_9)
        self.image_txt.setAlignment(QtCore.Qt.AlignCenter)
        self.image_txt.setObjectName("image_txt")
        self.gridLayout_5.addWidget(self.image_txt, 0, 0, 1, 1)
        self.ideallowpass_text = QtWidgets.QLabel(self.frame_9)
        self.ideallowpass_text.setAlignment(QtCore.Qt.AlignCenter)
        self.ideallowpass_text.setObjectName("ideallowpass_text")
        self.gridLayout_5.addWidget(self.ideallowpass_text, 0, 1, 1, 1)
        self.butterlowpass_text = QtWidgets.QLabel(self.frame_9)
        self.butterlowpass_text.setAlignment(QtCore.Qt.AlignCenter)
        self.butterlowpass_text.setObjectName("butterlowpass_text")
        self.gridLayout_5.addWidget(self.butterlowpass_text, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.base_image_label = QtWidgets.QLabel(self.frame_10)
        self.base_image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.base_image_label.setText("")
        self.base_image_label.setObjectName("base_image_label")
        self.gridLayout_8.addWidget(self.base_image_label, 0, 0, 1, 1)
        self.ideal_recons_label = QtWidgets.QLabel(self.frame_10)
        self.ideal_recons_label.setFrameShape(QtWidgets.QFrame.Box)
        self.ideal_recons_label.setText("")
        self.ideal_recons_label.setObjectName("ideal_recons_label")
        self.gridLayout_8.addWidget(self.ideal_recons_label, 0, 1, 1, 1)
        self.butter_recons_label = QtWidgets.QLabel(self.frame_10)
        self.butter_recons_label.setFrameShape(QtWidgets.QFrame.Box)
        self.butter_recons_label.setText("")
        self.butter_recons_label.setObjectName("butter_recons_label")
        self.gridLayout_8.addWidget(self.butter_recons_label, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.tab_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.origspectrum_text = QtWidgets.QLabel(self.frame_12)
        self.origspectrum_text.setAlignment(QtCore.Qt.AlignCenter)
        self.origspectrum_text.setObjectName("origspectrum_text")
        self.gridLayout_6.addWidget(self.origspectrum_text, 0, 0, 1, 1)
        self.idealspectrum_text = QtWidgets.QLabel(self.frame_12)
        self.idealspectrum_text.setAlignment(QtCore.Qt.AlignCenter)
        self.idealspectrum_text.setObjectName("idealspectrum_text")
        self.gridLayout_6.addWidget(self.idealspectrum_text, 0, 1, 1, 1)
        self.butterspectrum_text = QtWidgets.QLabel(self.frame_12)
        self.butterspectrum_text.setAlignment(QtCore.Qt.AlignCenter)
        self.butterspectrum_text.setObjectName("butterspectrum_text")
        self.gridLayout_6.addWidget(self.butterspectrum_text, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_12)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.origspectrum_label = QtWidgets.QLabel(self.frame_11)
        self.origspectrum_label.setFrameShape(QtWidgets.QFrame.Box)
        self.origspectrum_label.setText("")
        self.origspectrum_label.setObjectName("origspectrum_label")
        self.gridLayout_7.addWidget(self.origspectrum_label, 0, 0, 1, 1)
        self.idealspectrum_label = QtWidgets.QLabel(self.frame_11)
        self.idealspectrum_label.setFrameShape(QtWidgets.QFrame.Box)
        self.idealspectrum_label.setText("")
        self.idealspectrum_label.setObjectName("idealspectrum_label")
        self.gridLayout_7.addWidget(self.idealspectrum_label, 0, 1, 1, 1)
        self.butterspectrum_label = QtWidgets.QLabel(self.frame_11)
        self.butterspectrum_label.setFrameShape(QtWidgets.QFrame.Box)
        self.butterspectrum_label.setText("")
        self.butterspectrum_label.setObjectName("butterspectrum_label")
        self.gridLayout_7.addWidget(self.butterspectrum_label, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_11)
        self.verticalLayout_6.addWidget(self.frame_8)

        self.retranslate_ui()
        self.setLayout(self.verticalLayout_6)

        self.apply_ideal_lowpass_btn.clicked.connect(lambda : event_manager.trigger("on_apply_ideal_lowpass_filter"))
        self.apply_ideal_highpass_btn.clicked.connect(lambda : event_manager.trigger("on_apply_ideal_highpass_filter"))
        self.apply_butter_lowpass_btn.clicked.connect(lambda : event_manager.trigger("on_apply_butter_lowpass_filter"))
        self.apply_butter_highpass_btn.clicked.connect(lambda : event_manager.trigger("on_apply_butter_highpass_filter"))

        self.cutoff_edit.setText("0")
        self.n_butter_edit.setText("0")

        self.cutoff_edit.textChanged.connect(lambda x: event_manager.trigger("on_update_cutoff_frequency", x))
        self.n_butter_edit.textChanged.connect(lambda x: event_manager.trigger("on_update_n_butterworth", x))

        event_manager.register("on_load_image", self.update_image)
        event_manager.register("on_freq_image_result", self.update_result_image)


    def update_image(self, filepath:str):
        pixmap = QPixmap(filepath)
        self.base_image_label.setPixmap(pixmap)


    def update_result_image(self, image_name, image):
        pixmap = np_array_to_pixmap(image)
        if image_name == "original_spectrum":
            self.origspectrum_label.setPixmap(pixmap)
        elif image_name == "ideal_recons":
            self.ideal_recons_label.setPixmap(pixmap)
        elif image_name == "butter_recons":
            self.butter_recons_label.setPixmap(pixmap)
        elif image_name == "ideal_spectrum":
            self.idealspectrum_label.setPixmap(pixmap)
        elif image_name == "butter_spectrum":
            self.butterspectrum_label.setPixmap(pixmap)


    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.cutoff_text.setText(_translate("Lab2_Window", "Cutoff Frequency (D0)"))
        self.n_butterworth_text.setText(_translate("Lab2_Window", "N parameter for Butterworth  "))
        self.apply_ideal_lowpass_btn.setText(_translate("Lab2_Window", "Apply Ideal Low-Pass Filter"))
        self.apply_ideal_highpass_btn.setText(_translate("Lab2_Window", "Apply Ideal High-Pass Filter"))
        self.apply_butter_lowpass_btn.setText(_translate("Lab2_Window", "Apply Butterworth Low-Pass Filter"))
        self.apply_butter_highpass_btn.setText(_translate("Lab2_Window", "Apply Butterworth High-Pass Filter"))
        self.image_txt.setText(_translate("Lab2_Window", "Original Image"))
        self.ideallowpass_text.setText(_translate("Lab2_Window", " Ideal Low-Pass reconstructed Image 1"))
        self.butterlowpass_text.setText(_translate("Lab2_Window", "Low-Pass Butterworth reconstructed Image 1"))
        self.origspectrum_text.setText(_translate("Lab2_Window", "Original Spectrum"))
        self.idealspectrum_text.setText(_translate("Lab2_Window", "Ideal Low-Pass Spectrum 1"))
        self.butterspectrum_text.setText(_translate("Lab2_Window", "Low-Pass Butterworth Spectrum 1"))
