from PyQt5 import QtWidgets
from PyQt5 import QtCore
from PyQt5.QtGui import QPixmap, QIntValidator

from Lab2.utils import np_array_to_pixmap
from Lab2.events import event_manager



class SpatialFilterWidget(QtWidgets.QWidget):
    def __init__(self, parent=None, **kwargs) -> None:
        super().__init__(parent, **kwargs)

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_14.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(300, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")

        self.gridLayout_14.addWidget(self.frame_6, 0, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.border_dropdown = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.border_dropdown.sizePolicy().hasHeightForWidth())
        self.border_dropdown.setSizePolicy(sizePolicy)
        self.border_dropdown.setObjectName("comboBox_7")
        self.border_dropdown.addItem("")
        self.border_dropdown.addItem("")
        self.border_dropdown.addItem("")
        self.border_dropdown.addItem("")
        self.border_dropdown.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.border_dropdown)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.range_method = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.range_method.sizePolicy().hasHeightForWidth())
        self.range_method.setSizePolicy(sizePolicy)
        self.range_method.setObjectName("comboBox_6")
        self.range_method.addItem("")
        self.range_method.addItem("")
        self.range_method.addItem("")
        self.range_method.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.range_method)
        self.filter_method = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_method.sizePolicy().hasHeightForWidth())
        self.filter_method.setSizePolicy(sizePolicy)
        self.filter_method.setObjectName("comboBox_5")
        self.filter_method.addItem("")
        self.filter_method.addItem("")
        self.filter_method.addItem("")
        self.filter_method.addItem("")
        self.filter_method.addItem("")
        self.filter_method.addItem("")

        self.kernel_size_text = QtWidgets.QLineEdit(self.frame_2)
        self.kernel_size_text.setText(str(0))
        self.label_kernel_size = QtWidgets.QLabel(self.frame_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kernel_size_text)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_kernel_size)

        # self.filter_method.currentTextChanged.connect(lambda x: print(f"CHANGED {x}"))
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filter_method)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.gridLayout_14.addWidget(self.frame_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_3.addWidget(self.frame_5, 1, 0, 1, 1)

        self.label_3.setScaledContents(True)
        self.label_21.setScaledContents(True)

        self.kernel_size_text.setValidator(QIntValidator(1, 35))
        self.pushButton_2.clicked.connect(lambda: event_manager.trigger("on_apply_spatial_filter"))
        self.filter_method.currentTextChanged.connect(lambda x: event_manager.trigger("on_filter_method_changed", x))
        self.range_method.currentTextChanged.connect(lambda x: event_manager.trigger("on_range_method_changed", x))
        self.border_dropdown.currentTextChanged.connect(lambda x: event_manager.trigger("on_border_method_changed", x))
        self.kernel_size_text.textChanged.connect(lambda x: event_manager.trigger("on_kernel_size_changed", x))


        # self.filter_method.currentIndexChanged.connect(self.filterChanged)

        event_manager.register("on_load_image", self.update_image)
        event_manager.register("on_spatial_filter_result", self.update_result_image)

        self.setLayout(self.gridLayout_3)

        self.retranslateUi()


    def update_result_image(self, image):
        pixmap = np_array_to_pixmap(image)
        self.label_21.setPixmap(pixmap)


    def update_image(self, filepath:str):
        pixmap = QPixmap(filepath)
        self.label_3.setPixmap(pixmap)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Lab2_Window.setWindowTitle(_translate("Lab2_Window", "Lab2_Window"))
        self.pushButton_2.setText(_translate("Lab2_Window", "Apply Filter"))
        self.label_19.setText(_translate("Lab2_Window", "Handling Borders"))
        self.border_dropdown.setItemText(0, _translate("Lab2_Window", "0"))
        self.border_dropdown.setItemText(1, _translate("Lab2_Window", "None"))
        self.border_dropdown.setItemText(2, _translate("Lab2_Window", "Copy"))
        self.border_dropdown.setItemText(3, _translate("Lab2_Window", "Mirror"))
        self.border_dropdown.setItemText(4, _translate("Lab2_Window", "Circular"))
        self.label_18.setText(_translate("Lab2_Window", "Range"))
        self.range_method.setItemText(0, _translate("Lab2_Window", "Clamp 0 ... 255"))
        self.range_method.setItemText(1, _translate("Lab2_Window", "Abs and normalize to 255"))
        self.range_method.setItemText(2, _translate("Lab2_Window", "Abs and normalize 0 to 255"))
        self.range_method.setItemText(3, _translate("Lab2_Window", "Normalize 0 to 255"))
        self.filter_method.setItemText(0, _translate("Lab2_Window", "Mean"))
        self.filter_method.setItemText(1, _translate("Lab2_Window", "Gaussian"))
        self.filter_method.setItemText(2, _translate("Lab2_Window", "Median "))
        self.filter_method.setItemText(3, _translate("Lab2_Window", "Sobel x-axis"))
        self.filter_method.setItemText(4, _translate("Lab2_Window", "Sobel y-axis"))
        self.filter_method.setItemText(5, _translate("Lab2_Window", "Sobel"))
        self.label_17.setText(_translate("Lab2_Window", "Filter Type"))
        self.label_kernel_size.setText(_translate("Lab2_Window", "Kernel size"))
        self.label.setText(_translate("Lab2_Window", "Original Image"))
        self.label_2.setText(_translate("Lab2_Window", "Filtered Image"))